FROM python:3
USER root

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8

RUN apt-get install -y vim less && apt clean && rm -rf /var/lib/apt/lists/*

ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN python -m pip install jupyterlab

# docker compose up -d --build
# docker container ls
# docker compose exec python3 bash
# python --version
# cd opt
# python sample.py 180.0
# python show_ip.py
# docker compose down
# docker rm $(docker ps --all -q)
# docker rmi $(docker images -q)
